- autoload/vista/finder/fzf.vim
Hitting `/` in the sidebar caused an error
> Fix find error in sidebar

- autoload/vista/executive/coc.vim
- autoload/vista/finder/fzf.vim
Removed warning messages to avoid press enter prompt
> Make Finder fall back on alternative executive

- autoload/vista.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/finder/fzf.vim
- also add the guard statements to see if the prerequsite has been
satisfied.
> Flexible executive options

- README.md
- autoload/vista/cursor.vim
- autoload/vista/error.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/floating.vim
- autoload/vista/source.vim
- doc/vista.txt
Closes #18 
It's usable now, but still need to take care of some details.
> Support showing current symbol in the floating win

- README.md
- autoload/vista.vim
- autoload/vista/error.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/parser/ctags.vim
> Utilize the option --output-format=json

- README.md
- autoload/vista.vim
- autoload/vista/autocmd.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/finder/fzf.vim
- doc/vista.txt
- support LanguageClient-neovim
- add provider in statusline
> Add initial LCN support

- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/executive/vim_lsp.vim
- autoload/vista/sidebar.vim
- doc/vista.txt
Ref https://github.com/liuchengxu/vista.vim/issues/34#issuecomment-477503223
> Execute without check

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- autoload/vista/autocmd.vim
- autoload/vista/cursor.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/parser/ctags.vim
- autoload/vista/renderer.vim
- autoload/vista/renderer/default.vim
- autoload/vista/renderer/line.vim
- autoload/vista/sidebar.vim
- autoload/vista/source.vim
- autoload/vista/viewer.vim
- doc/vista.txt
- syntax/vista.vim
> Support nested display

- README.md
- autoload/vista/executive/ctags.vim
- autoload/vista/floating.vim
- autoload/vista/parser/ctags.vim
- autoload/vista/renderer/default.vim
- autoload/vista/util.vim
> Remove PF fields for json mode

- autoload/vista/renderer/default.vim
> Add scope in s:DesendentsOf

- autoload/vista/cursor.vim
- autoload/vista/util.vim
- doc/vista.txt
> Add scroll strategy for showing details of tag

- autoload/vista/cursor.vim
- autoload/vista/popup.vim
- doc/vista.txt
> Support vim popup

- autoload/vista.vim
- autoload/vista/cursor.vim
- autoload/vista/jump.vim
- doc/vista.txt
- ftplugin/vista.vim
> Add shortcuts for going to the top-level tag

- autoload/vista/popup.vim
> Don't make popup intrusive

- README.md
- autoload/vista/executive/ale.vim
- doc/vista.txt
- plugin/vista.vim
> Add support for ALE

- autoload/vista/cursor.vim
- autoload/vista/types/uctags/config.vim
> Support getting the nearest symbol

- README.md
Here is a proposal for an imho clearer documentation. Feel free to change the wording if you don't like it. I didn't add screenshots because my color setup wouldn't really fit in with the rest of the README, but I think it should be clear enough anyway.
Closes #127
> Clarify documentation of LSP tags view

- autoload/vista/finder/fzf.vim
- autoload/vista/renderer.vim
> Append icon for the fzf items

- autoload/vista/renderer.vim
- autoload/vista/renderer/default.vim
Close #74
- FuraCode Nerd Font
- alacritty
> More icons

- autoload/vista/autocmd.vim
- autoload/vista/cursor.vim
- autoload/vista/floating.vim
- autoload/vista/fold.vim
- autoload/vista/popup.vim
- autoload/vista/renderer/default.vim
- autoload/vista/util.vim
- doc/vista.txt
- ftplugin/vista.vim
- syntax/vista.vim
> Refine the fold display

- autoload/vista/executive/coc.vim
- autoload/vista/finder.vim
> Rework coc finder as data of coc has been changed to a List

- autoload/vista/executive/ale.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/executive/vim_lsc.vim
- autoload/vista/executive/vim_lsp.vim
- autoload/vista/floating.vim
- autoload/vista/popup.vim
- autoload/vista/renderer.vim
> Refactor LSP and popup/floating

- autoload/vista/cursor.vim
- autoload/vista/util.vim
Previously, the highlight is only correct when the cursor is in Vista's window. Fixes #197
> Try to highlight the exact tag all the time

- autoload/vista/floating.vim
- autoload/vista/popup.vim
> Fix regression on #194

- autoload/vista/autocmd.vim
- autoload/vista/cursor.vim
> Fix tab switching issue

- autoload/vista/types/uctags/go.vim
A few fixes for gotags
- Add methods
- Add interfaces
- Fix struct members tag
- Fix imports
> Fixes for gotags

- autoload/vista/ftplugin.vim
- doc/vista.txt
> add an option to disable default mappings

- autoload/vista/finder/fzf.vim
Blink line after jumping to the target through finder.
> Make finder blinkable

- README.md
- autoload/vista.vim
- autoload/vista/autocmd.vim
- autoload/vista/parser/lsp.vim
- autoload/vista/renderer.vim
- autoload/vista/renderer/kind.vim
- autoload/vista/renderer/markdown_like.vim
- syntax/vista_kind.vim
You might like this if you are using coc-explorer.
> Update default toc icons

- plugin/vista.vim
Hi, maintainer.
This patch also check to duplicate.
Could you check this Pull Request?
> [add] check Duplicate

- autoload/vista/parser/ctags.vim
> Parser#ctags#FromExtendedRaw: return if line is only whitespace

- autoload/vista/executive/ctags.vim
> fix: ctags text_chage read exception all catch

- autoload/vista/parser/ctags.vim
Stridx regular expression does not work properly with single quotes
> Change stridx single quote to double quote

- autoload/vista/popup.vim
Recreated PR #310 which was closed prematurely.
Please feel free to close this if this functionality is not desired.
> Popups close themselves

- CHANGELOG.md
- autoload/vista.vim
- autoload/vista/autocmd.vim
- autoload/vista/debugging.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/init.vim
- autoload/vista/renderer.vim
- autoload/vista/toc.vim
- doc/vista.txt
Add `g:vista_log_file` for debugging purpose, and fix some auto update disorder issues.
> Impl logging feature

- README.md
- autoload/vista/finder.vim
- plugin/vista.vim
See: https://github.com/junegunn/fzf.vim/commit/4145f53
Fixes #329
> fix fzf preview range

- syntax/vista.vim
- syntax/vista_kind.vim
Closes https://github.com/romgrk/barbar.nvim/issues/62
> fix: dont define g:icons in syntax files

- autoload/vista/renderer/hir/lsp.vim
> Don't skip the last elment when rendering for coc

- autoload/vista.vim
> Fix https://github.com/liuchengxu/vista.vim/issues/385

- autoload/vista.vim
- autoload/vista/cursor.vim
- autoload/vista/executive/ale.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/executive/nvim_lsp.vim
- autoload/vista/executive/vim_lsc.vim
- autoload/vista/executive/vim_lsp.vim
> Try initial run for the nearest function on startup

- .github/workflows/ci.yml
- autoload/vista/executive/nvim_lsp.vim
> Reset nvim_lsp_fetching to true before RunAsync

- autoload/vista/renderer/kind.vim
> fix(sort): fix #280

- autoload/vista/types/uctags/go.vim
- autoload/vista/types/uctags/tex.vim
> Update types for go and tex

- autoload/vista/finder.vim
After the updating of fzf.vim, the results of  fzf#vim#preview has been changed, so the correspondent part of finder.vim should be modified
> fixed toggle key bug incomparable with fzf.vim

- README.md
- autoload/vista/executive/yegappan_lsp.vim
- doc/vista.txt
> Added support to yeagappan lsp
