liuchengxu/vista.vim

- README.md
- autoload/vista/cursor.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/executive/vim_lsp.vim
- autoload/vista/parser/ctags.vim
- autoload/vista/parser/lsp.vim
- autoload/vista/util.vim
- doc/vista.txt
- ftplugin/vista.vim
```vim
function! NearestMethodOrFunction() abort
return exists('b:vista_nearest_method_or_function') ? b:vista_nearest_method_or_function : ''
endfunction
set statusline+=%{NearestMethodOrFunction()}
```
Also refer to https://github.com/liuchengxu/eleline.vim/pull/18.
> Implement finding nearest method or function

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- autoload/vista.vim
- autoload/vista/cursor.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/finder/fzf.vim
- autoload/vista/parser/ctags.vim
- autoload/vista/renderer/default.vim
- autoload/vista/renderer/kind.vim
- autoload/vista/sidebar.vim
- autoload/vista/source.vim
- autoload/vista/util.vim
- doc/vista.txt
- ftplugin/vista.vim
- syntax/vista.vim
This PR is the first step of #30, still missint the nested feature for now. But some other features are usable(with bug apparently) via `:let g:vista_ctags_renderer = 'default' | Vista` :
- highlight the nearest tag in the vista window automatically.
- when the vista sidebar is open, `:Vista show` jumps to the location of current nearest tag.
- lots of refactoring stuff.
-  fixes #31, use `:let g:vista_ctags_renderer = 'default' | Vista show` for now.
I choose the leave the doc behind since it's still experimental, but testers are highly welcome.
I'll continue to work on the nested feature after merging this.
> Provide default renderer

- autoload/vista.vim
- autoload/vista/error.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/executive/vim_lsp.vim
- autoload/vista/extension/markdown.vim
- autoload/vista/finder/fzf.vim
- autoload/vista/parser/ctags.vim
- autoload/vista/parser/lsp.vim
- autoload/vista/renderer/markdown.vim
- autoload/vista/types/uctags/python.vim
- doc/vista.txt
Closes #19.
The future work:
- searching the header regex instead of iterating the whole buffer? refer to vim-markdown-toc. Still not sure if it's better.
- an async external parser
- https://github.com/jonschlinkert/markdown-toc
- https://github.com/pbzweihander/markdown-toc
> Add markdown extension

- autoload/vista/cursor.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/ctags.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/executive/vim_lsp.vim
- autoload/vista/extension/markdown.vim
- autoload/vista/renderer/default.vim
- autoload/vista/source.vim
- autoload/vista/util.vim
- syntax/vista.vim
- syntax/vista_kind.vim
- syntax/vista_markdown.vim
- fix syntax mismatch when switching between the executives, e.g., `:Vista coc` and then `Vista ctags`.
- add vista_markdown syntax.
> Fix syntax loading and refactoring

- autoload/vista/finder/fzf.vim
`expand('%S')` no longer produces the right file
> Fix fzf finder preview

- autoload/vista/finder/fzf.vim
Enabling devicons breaks fzf finder preview. This happens due to icons being injected into the preview command ahead of line number, breaking fzf.vim preview script.
This PR adds a simplistic change, utilizing field index to instead inject only a line number, which resides in the first field if devicons are not enabled and in the second one is they are.
> Make fzf finder work with devicons

- README.md
- autoload/vista.vim
- autoload/vista/finder.vim
- autoload/vista/finder/fzf.vim
- autoload/vista/finder/skim.vim
- doc/vista.txt
Close #129
The dependency is [skim](https://github.com/lotabout/skim) only, no need to install [skim.vim](https://github.com/lotabout/skim.vim).
`:Vista finder skim:ctags`:
> Add skim support

- autoload/vista/executive/ctags.vim
neovim version: NVIM v0.5.0-10-g0b71bb73e
I've trying to figure out the following error when using fzf tabopen action with autocmd calling `vista#RunForNearestMethodOrFunction`:
```
Error detected while processing function vista#cursor#FindNearestMethodOrFunction:
line    1:
E716: Key not present in Dictionary: source.bufnr
```
Then I figure out that `t:vista` may not exist because of neovim autocmd event order.
neovim may emit `CursorMoved` before `BufRead` when using fzf tabopen
action. Thus vista.vim cannot update buffer info before execute.
This fix might need to be applied to other executives. But I'm not sure where should I add the similiar check for other executives.
> Don't execute async callback if t:vista is not exists

- doc/vista.txt
The `/` command was removed in 2662f45ef.
Also add documentation about how to add the mapping again.
> doc: remove / from the list of command

- autoload/vista/parser/lsp.vim
According to the [document](https://microsoft.github.io//language-server-protocol/specifications/specification-3-14/#textDocument_documentSymbol), response type of `Document Symbols` request is `DocumentSymbol[] | SymbolInformation[] | null`. Current implementation only supports `SymbolInformation`, so I added `DocumentSymbol` support.
Tested in `vim-lsp` and golang(`gopls`) with `:Vista vim_lsp` command.
> Support DocumentSymbol type in vim_lsp executive

- autoload/vista/executive/ctags.vim
- autoload/vista/renderer/default.vim
Since UCtags can generate anonymous tags itself (and I belive it's the only ctags implementation that works with Vista) it's possible to dump manual __anon tags generation at all.
Sample C++ file:
```
struct {
int bar;
} anon;
namespace example {
struct {
int foo;
};
struct {
int bar;
};
enum {
FOO
};
enum {
BAR
};
}
namespace {
enum {
BAZ
};
}
int
main(void)
{
return 0;
}
```
This commit also fixes numerous bugs (e.g. Vista can't handle two anonymous enums in a single namespace).
> Generate tags for anonymous entities (C/C++)

- autoload/vista/renderer/default.vim
This patch allows Vista to handle C++ one-line namespace like this:
namespace foo::bar::baz { ... };
Probably gonna fix other languages that permit similar syntax.
This patch can break things so it would be nice to do some smoke testing at least on Rust (see https://github.com/universal-ctags/ctags/issues/2065#issuecomment-485117935).
Sample C++ file:
```
namespace foo::bar::baz {
int x;
};
int main(void)
{
return 0;
}
```
> Allow parent tags on the same line

- autoload/vista/cursor.vim
Always jump to the tag under cursor when `<CR>` is pressed, no matter whether it is highlighted or echoed. Fixes #191
> More reliable tag jump

- autoload/vista/floating.vim
- autoload/vista/popup.vim
Check whether the user is still in the Vista window before displaying the floating window. Fixes #194
> Prevent floating_win from show up in other window

- autoload/vista.vim
- autoload/vista/cursor.vim
- autoload/vista/cursor/ctags.vim
- autoload/vista/cursor/lsp.vim
- autoload/vista/echo.vim
- autoload/vista/executive/coc.vim
- autoload/vista/executive/lcn.vim
- autoload/vista/highlight.vim
- autoload/vista/jump.vim
- autoload/vista/lsp.vim
- autoload/vista/sidebar.vim
- autoload/vista/source.vim
- autoload/vista/util.vim
- autoload/vista/win.vim
- Split out the ctags and LSP logic in cursor.vim.
- Split out echo function into `echo.vim`.
> Refactoring cursor.vim

- README.md
brew will fail to tap with the `--with-jansson` flag because it doesn't know it's a flag before tapping, and this particular tap formula requires `--HEAD`:
```bash
$ brew install --with-jansson universal-ctags/universal-ctags/universal-ctags
...
Error: invalid option: --with-jansson
$ brew tap brew tap universal-ctags/universal-ctags
...
$  brew install --with-jansson universal-ctags/universal-ctags/universal-ctags
Error: universal-ctags/universal-ctags/universal-ctags is a head-only formula
Install with `brew install --HEAD universal-ctags/universal-ctags/universal-ctags`
$  brew install --with-jansson --HEAD universal-ctags/universal-ctags/universal-ctags
```
> Updated macOS brew command for universal-ctags

- autoload/vista/finder.vim
With current implementation, even though `g:vista#renderer#enable_icon` is set to `0`, a unnecessary space appears in head of each lines like below:
```
fzf:lcn>   < 83/83
>  47:Flag               [Method]     Flag(c int) bool
44:Precision          [Method]     Precision() (prec int, ok bool)
42:Width              [Method]     Width() (wid int, ok bool)
40:Write              [Method]     Write(b []byte) (n int, err error)
54:Format             [Method]     Format(f State, c rune)
63:String             [Method]     String() string
71:GoString           [Method]     GoString() string
...
```
So, this PR removes such a space from rows like below:
```
fzf:lcn>   < 83/83
> 47:Flag               [Method]     Flag(c int) bool
44:Precision          [Method]     Precision() (prec int, ok bool) …
```
> Remove a unnecessary head space from finder rows when icon rendering is disabled

- autoload/vista/finder/fzf.vim
#229 breaks jumping behaviour of finder.
This PR fix the bug for fzf.
> fix breaking fzf jumping behaviour introduced in #229

- autoload/vista/finder.vim
- autoload/vista/finder/fzf.vim
Switch positions of line number and tag in finder rows like below:
In the normal vista window, tags place before line numbers like below. I think finder's columns order should be same as the window. Furthermore, tags which I think we might be most interested in will be aligned by this change like `After` image.
Does this make sense?
> Switch line number and tag in finder rows

- autoload/vista/finder/fzf.vim
With current implementation, `FZFVistaBracket` affects undesired brackets like below: (pay attention to `[]` before `byte`)
This PR make `FZFVistaBracket` more correctly like below:
Even though this is still not perfect, I think this highlight rules can cover in most cases.
> Make FZFVistaBracket more correctly

- autoload/vista/renderer/default.vim
- syntax/vista.vim
Show the icon at the beginning as what most other tools do, e.g., IDEA>Structures.
Before:
Now:
> Change ctags renderer format

- autoload/vista/echo.vim
- autoload/vista/highlight.vim
More safely and accurately to find the starting position of the accurate
tag. Avoid pattern matching, as the tag name may contain "~".
I found this bug when I use vista.vim to browse a qt project.
The destructor of the qt class is indicated by adding `~` in front of the corresponding constructor.
error:
fix:
> Fix echo error in cmdline when the tag name contain "~".

- autoload/vista/finder/fzf.vim
Running `finder` on the entire project (i.e. using `:Vista finder!`) doesn't currently work because too many arguments are being passed to `s:ApplyRun`. I've made some minor changes to fix this and still keep highlighting. 
PS. Is there a way to enable preview for `finder` with project-wide tags?
>  Fix bug with passing too many arguments to function when running finder on entire project

- autoload/vista/types/uctags/tex.vim
In universal-ctags/ctags@942142fa061815f32dc4babe3d8116bf8400eb4f support for frames was added to universal ctags. The g and f kinds have been added to support it in vista.vim
> Added types for Beamer TeX class

- autoload/vista/finder.vim
**Note**: same as #248 but excludes the fix from Win32 as per [this request](https://github.com/liuchengxu/vista.vim/pull/248#issuecomment-597992430)
The FZF Preview has been broken ever since #231 when the positions of object/function name and line number were switched. This PR uses grep to grab the line number only and pass it to fzf preview.sh in the format it expects.
See https://github.com/liuchengxu/vista.vim/pull/231#issuecomment-595985345 for more details
> Fix FZF Preview (no win32)

- autoload/vista/parser/ctags.vim
Errors from ctags had no tabs in them, so splitting them didn't give
enough indexes. Now, if no tabs or all whitespace, just return
Also add an error message if ctags output parsing fails.
> vista#parser#ctags#FromExtendedRaw: Return on unparsable ctags output

- autoload/vista/executive/coc.vim
- autoload/vista/parser/lsp.vim
- autoload/vista/renderer/hir/lsp.vim
Previously, if I had the `:Vista coc` pane open but my cursor was in the code
window, no tag would be highlighted in the vista pane. The `:Vista ctags` pane
would correctly highlight the nearest tag from where my cursor was in the code.
I discovered that this was because the global variables `g:vista.functions` and
`g:vista.raw` are not set when using the coc executive.
This change populates those two globals from list of symbols in the response
from coc. Similar to what happens with the ctags renderer, the `vlnum` values in
`g:vista.raw` are later filled in during rendering the vista window contents.
Working nearest tag highlighting for `:Vista coc`:
[![asciicast](https://asciinema.org/a/TBtsLYsmYx6dEqvKS6kcUZSAl.svg)](https://asciinema.org/a/TBtsLYsmYx6dEqvKS6kcUZSAl)
> Highlight nearest tag for coc renderer

- autoload/vista/renderer/hir/lsp.vim
Since all other groups are spaced out with an empty line, it looked wrong that
there was no empty line between the hierarchical tag groups and the tags grouped
by kind.
Before:
After:
> Add line between coc leveled tags and tags by kind

- autoload/vista/cursor/lsp.vim
No matter which echo strategy the user choose, as soon as the `nvim_lsp` strategy is in use it does not work to show details of the current tag under cursor. This is due to a missing implementation to extract the tag of the current Vista buffer line for the `nvim_lsp` provider. Such has been added. As result the user can now use the `p` mapping within the Vista window, as well as the `g:vista_echo_cursor` option.
> Add show detail support for nvim_lsp provider

- autoload/vista/finder/fzf.vim
When there is a [:num] structure in codes (which is common in python), FZFVistaTag highlight group will be mismatched. This pr includes a more strict regex to fix it.
Another problem is that FZFVistaScope highlight group will highlight codes in the fzf preview window, I also slightly modified the regex to fix it.
Some examples can be found in [#264](https://github.com/liuchengxu/vista.vim/issues/264).
Thank you!
> More strict regex for FZFVistaTag and FZFVistaScope to prevent the preview codes from being highlighted

- autoload/vista/executive/ctags.vim
- As of ctags commit `cf82cfa2` --file-scope is obsolete.
- use `--extras=+F` instead.
> Don't use obsolete ctags option --file-scope

- autoload/vista/toc.vim
[API Blueprint](https://apiblueprint.org/documentation/specification.html) is a set of semantic assumptions on top of markdown, so the TOC mechanism can render this without an issue.
With this small change, when installing [apiblueprint.vim](https://github.com/kylef/apiblueprint.vim) and configuring vista.vim as following, the table of contents is rendered correctly:
```viml
let g:vista_executive_for = {
\ 'apiblueprint': 'markdown',
\ }
```
> Support API Blueprint for TOC rendering

- README.md
In case is useful for someone else
> Add fedora steps to install ctags with json support

- autoload/vista/finder.vim
Add fnameescape() to the g:vista.source.fpath, so that the fzf.vim preview function correctly for files with paths containing spaces. Fix issue #307 
Screenshot of preview:
Screenshot of file path (in statusline):
> Escape spaces in file path when running fzf.vim preview

- autoload/vista/cursor.vim
Popups/floating windows currently always preview the start of the file in both Vim and neovim, because a `msg` is erroneously passed to `vista#win#FloatingDisplayOrPeek()` instead of `lnum`
> Display correct line in floating windows/popups

- autoload/vista/parser/ctags.vim
Adds support in vista#parser#ctags#FromExtendedRaw for handling ';"'
when present in source code line.
When the ';"' string is present in a source code line, it breaks vista#parser#ctags#FromExtendedRaw.
This causes the same behavior as in Issue #340.
> Updates ctags parsing for handling ';"' in source line.

- README.md
nvim-lsp was renamed to nvim-lspconfig and previously the link was pointing to nvim rather than nvim-lspconfig.
> Change nvim-lsp to nvim-lspconfig and change link

- autoload/vista/executive/nvim_lsp.vim
During debugging #355 i found out that errors are swallowed by the callback and it's assumed that execution can proceed. This adds some error handling to the callback and makes debugging these errors easier.
> print errors if they occur in vim_lsp executor

- autoload/vista/finder.vim
After https://github.com/liuchengxu/vista.vim/pull/330 has been merged, the FZF preview window is forcibly displayed even though the `g:vista_fzf_preview` isn't configured.
This PR makes the FZF preview window be displayed only when it's needed (when `g:vista_fzf_preview` is configured).
> fzf: render preview window when it's needed

- autoload/vista/finder.vim
#330 add the line number to the end of each candidate line in the fzf selector. 
However, since each line already has the line number, it is just redundant.
This PR removes the redundant duplicated line number from the fzf selector.
> fzf: remove duplicated line number

- autoload/vista/toc.vim
When the user, such as one using vim-pandoc-syntax, changes the filetype to `pandoc.markdown`, this patch makes sure the toc will still work. [This](https://github.com/vim-pandoc/vim-pandoc-syntax#standalone) explains why the user has the motivation to change the filetype. Thanks!
> Better support for complex Markdown/Pandoc filetype.

- autoload/vista.vim
- autoload/vista/finder/fzf.vim
Issue [385](https://github.com/liuchengxu/vista.vim/issues/385)
it closes the sidebar  when the finder is executed and remove the close sentence if the command `:Vista` doesn't
have arguments
After the PR [391](https://github.com/liuchengxu/vista.vim/pull/391) the flag continues with the issue as it is commented by  [derekschrock](https://github.com/liuchengxu/vista.vim/issues/385#issuecomment-786708985)
[video explanation](https://www.youtube.com/watch?v=vxD96e-2uRU)
> Fixing with flag vista_close_on_fzf_select

- README.md
The latest tap does not have an optional `--with-jansson` option
anymore, it's installed by default since
[February 23 2021](https://github.com/universal-ctags/homebrew-universal-ctags/commit/82db2cf9cb0cdecf62ca9405e767ec025b5ba8ed)
Calling the install command with the `--with-jansson` option would
return an error from Homebrew.
```
Error: invalid option: --with-jansson
```
In time the whole macOS instructions can probably be removed, but since
the change was made recently, existing installs may need to reinstall
ctags before it works with the JSON feature.
> Update jansson dependency instructions for macOS

- autoload/vista/jump.vim
if tag contains regex charactors (such as / - $ etc), may matchstrpos maybe failed.
if tag is [4-2] , matchstrpos will throw error blow:
```
Error detected while processing function vista#cursor#FoldOrJump[9]..vista#jump#TagLine:                                                                                              
line   16:
E944: Reverse range in character class
```
> [fix] jump to a line contains regex escape charactors may failed

- autoload/vista/executive/nvim_lsp.vim
> nvim_lsp: fix compatibility with neovim 0.6+

- autoload/vista/finder.vim
LSP objects in Vista during FZF search are displayed as
<element>:<line_number>. In the Fuzzy Finder search we wanted search
only over the <element> part. It was achieved by defining search target
as everything up to the first colon. Such behavior was problematic in
languages like C++, where colon is a valid character for LSP object name
(it's denoting namespaces). For names like MyNamespace::MyClass::method
fuzzy finding didn't work properly and we could only search by the text
up to first colon.
The problem was fixed by changing the line number delimiter to be
the last colon.
> Fix Fuzzy Finder search when element contains colon

- autoload/vista/executive/ale.vim
With latest ALE, Vista does not seem to work anymore. It seems the function name changed. The change in this PR fixes it for me (although i didn't do extensive testing).
> fix ale function call

- autoload/vista/floating.vim
- doc/vista.txt
- plugin/vista.vim
Closes #432 
Add `g:vista_floating_border` option which allows the user to change the border that vista uses for the floating preview.
Screenshot where I configured my neovim to use the `rounded` option:
> Enhancement: add floating border config option

- autoload/vista/finder/fzf.vim
With a language like `Go`, which may have square brackets in a tag (e.g. in Go, it may have `(*MyType[T]).MyMethod` in a tag if we use Generics), current line number extraction logic raise an error since it's splitting a line with a square bracket like `split(a:line, '[')[0])`. This PR tries to fix this kind of error.
> fzf: fix line number extraction

- autoload/vista/highlight.vim
Fixes a bug where the following E803 error happens as soon as the blinking highlight disappears.
> fix: Ignore E803 error while trying to delete temporary highlight

- autoload/vista.vim
- autoload/vista/init.vim
- autoload/vista/sidebar.vim
- autoload/vista/source.vim
Addresses #430.
This avoids updating the Vista sidebar just once with on BufEnter. This is enough to at least get `:Vista focus` to stop resetting the sidebar.
> Added a skip_once_flag to skip updating once

- autoload/vista/executive/ctags.vim
Hi @liuchengxu, 非常感谢你创建了这么 Nice 的插件，不过在使用途中发现一些小小的问题，比如我自定义了 ruby 文件使用 `ripper-tags` 解析，但是因为我的 typo 我始终无法正确显示 ctags 侧边栏，最终花费了大量时间定位问题。
之前的异步处理没有处理错误情况，当 shell 命令失败之后直接静默掉，即使启用了 `g:vista_log_file` 也无法定位问题，这个 pr 增加了一些错误处理的逻辑，可以将错误直接提示给用户，减少用户发起 issue 的可能。
> Echo error explicitly

- autoload/vista/source.vim
The winid tracked in g:vista.source is not correct. So use g:vista.source.bufnr to get the correct winid and jump.
Close #416
> Fix jump to wrong window in multi-tab

- autoload/vista/parser/lsp.vim
When the symbol text is multi-line, the behavior when hovering the cursor is not correct.
This pull request is a fix for symbol text not being multi-line.
> Avoid multi-line symbols
